name: log commit ID

on: 
  push:


jobs:
  log-commit:
    runs-on: ubuntu-latest


    steps:
      - name: Add Commit Id to log
        run: |
          echo "commit ID: $GITHUB_SHA" >> commit.log
          echo "Commit time: $(git show -s --format=%cI $GITHUB_SHA)" >> commit.log
          echo "Commit log: $(git show -s --format=%B $GITHUB_SHA)" >> commit-log
            
            cat commit.log  
